In [1]:
from sims import *

In [2]:
synthetic_info = dataGenerate(seed = 7, train_samples = 3000, test_samples = 100)

In [3]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "threshold adjusting", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 1, local_epochs = 1, alpha = 1, train_prn = False, adaptive_alpha = True, seed = 7)

  0%|          | 0/1 [00:00<?, ?it/s]


 | Global Training Round : 1 |

Client 0: accuracy loss: 19.98 | fairness loss 0.94 | Demographic disparity = 0.56


100%|██████████| 1/1 [00:00<00:00,  4.23it/s]

Client 1: accuracy loss: 16.05 | fairness loss 1.55 | Demographic disparity = 0.35
Client 2: accuracy loss: 11.86 | fairness loss 1.26 | Demographic disparity = 0.33
 
Avg Training Stats after 1 global rounds:
Training loss: 243.05 | Validation accuracy: 15.67% | Validation Demographic disparity: 0.3799
tensor([ 470.7816, -470.7816])
tensor([ 168.0826, -168.0826])
tensor([ 80.5182, -80.5182])
 
 Results after 1 global rounds of training:
|---- Avg Train Accuracy: 15.67%
|---- Test Accuracy: 16.00%
|---- Test Demographic disparity: 0.4505

 Total Run Time: 0.3978 sec


In [3]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, train_prn = False, adaptive_alpha = True, seed = 7)

  0%|          | 0/10 [00:00<?, ?it/s]


 | Global Training Round : 1 |



 10%|█         | 1/10 [00:02<00:18,  2.10s/it]

Client 1: accuracy loss: 2.74 | fairness loss 0.86 | Demographic disparity = 0.53
Client 2: accuracy loss: 2.54 | fairness loss 1.44 | Demographic disparity = 0.34
Client 3: accuracy loss: 2.30 | fairness loss 1.16 | Demographic disparity = 0.32
 
Avg Training Stats after 1 global rounds:
Training loss: 37.30 | Training accuracy: 87.55% | Training Demographic disparity: 0.3829

 | Global Training Round : 2 |



 20%|██        | 2/10 [00:04<00:16,  2.12s/it]

Client 1: accuracy loss: 2.70 | fairness loss 0.38 | Demographic disparity = 0.32
Client 2: accuracy loss: 2.96 | fairness loss 0.65 | Demographic disparity = 0.28
Client 3: accuracy loss: 2.59 | fairness loss 0.55 | Demographic disparity = 0.18
 
Avg Training Stats after 2 global rounds:
Training loss: 44.05 | Training accuracy: 86.86% | Training Demographic disparity: 0.2455

 | Global Training Round : 3 |



 30%|███       | 3/10 [00:06<00:15,  2.15s/it]

Client 1: accuracy loss: 2.87 | fairness loss 0.33 | Demographic disparity = 0.23
Client 2: accuracy loss: 3.52 | fairness loss 0.54 | Demographic disparity = 0.18
Client 3: accuracy loss: 3.39 | fairness loss 0.51 | Demographic disparity = 0.09
 
Avg Training Stats after 3 global rounds:
Training loss: 44.31 | Training accuracy: 82.27% | Training Demographic disparity: 0.1439

 | Global Training Round : 4 |



 40%|████      | 4/10 [00:09<00:13,  2.26s/it]

Client 1: accuracy loss: 3.08 | fairness loss 0.33 | Demographic disparity = 0.16
Client 2: accuracy loss: 4.18 | fairness loss 0.52 | Demographic disparity = 0.11
Client 3: accuracy loss: 4.26 | fairness loss 0.53 | Demographic disparity = 0.03
 
Avg Training Stats after 4 global rounds:
Training loss: 43.82 | Training accuracy: 78.75% | Training Demographic disparity: 0.0784

 | Global Training Round : 5 |



 50%|█████     | 5/10 [00:11<00:11,  2.23s/it]

Client 1: accuracy loss: 3.29 | fairness loss 0.34 | Demographic disparity = 0.03
Client 2: accuracy loss: 4.79 | fairness loss 0.51 | Demographic disparity = 0.05
Client 3: accuracy loss: 5.02 | fairness loss 0.55 | Demographic disparity = 0.02
 
Avg Training Stats after 5 global rounds:
Training loss: 43.30 | Training accuracy: 74.98% | Training Demographic disparity: 0.0095

 | Global Training Round : 6 |



 60%|██████    | 6/10 [00:13<00:08,  2.24s/it]

Client 1: accuracy loss: 3.06 | fairness loss 0.43 | Demographic disparity = 0.13
Client 2: accuracy loss: 4.32 | fairness loss 0.65 | Demographic disparity = 0.10
Client 3: accuracy loss: 4.57 | fairness loss 0.67 | Demographic disparity = 0.02
 
Avg Training Stats after 6 global rounds:
Training loss: 43.16 | Training accuracy: 78.04% | Training Demographic disparity: 0.0653

 | Global Training Round : 7 |



 70%|███████   | 7/10 [00:15<00:06,  2.27s/it]

Client 1: accuracy loss: 3.10 | fairness loss 0.42 | Demographic disparity = 0.13
Client 2: accuracy loss: 4.40 | fairness loss 0.63 | Demographic disparity = 0.10
Client 3: accuracy loss: 4.69 | fairness loss 0.65 | Demographic disparity = 0.02
 
Avg Training Stats after 7 global rounds:
Training loss: 43.04 | Training accuracy: 78.04% | Training Demographic disparity: 0.0653

 | Global Training Round : 8 |



 80%|████████  | 8/10 [00:17<00:04,  2.26s/it]

Client 1: accuracy loss: 3.51 | fairness loss 0.36 | Demographic disparity = 0.01
Client 2: accuracy loss: 5.41 | fairness loss 0.52 | Demographic disparity = 0.02
Client 3: accuracy loss: 5.79 | fairness loss 0.59 | Demographic disparity = 0.02
 
Avg Training Stats after 8 global rounds:
Training loss: 42.74 | Training accuracy: 74.37% | Training Demographic disparity: 0.0102

 | Global Training Round : 9 |



 90%|█████████ | 9/10 [00:20<00:02,  2.24s/it]

Client 1: accuracy loss: 3.21 | fairness loss 0.44 | Demographic disparity = 0.09
Client 2: accuracy loss: 4.71 | fairness loss 0.64 | Demographic disparity = 0.07
Client 3: accuracy loss: 5.09 | fairness loss 0.68 | Demographic disparity = 0.01
 
Avg Training Stats after 9 global rounds:
Training loss: 42.71 | Training accuracy: 76.38% | Training Demographic disparity: 0.0401

 | Global Training Round : 10 |



100%|██████████| 10/10 [00:22<00:00,  2.27s/it]

Client 1: accuracy loss: 3.15 | fairness loss 0.45 | Demographic disparity = 0.13
Client 2: accuracy loss: 4.60 | fairness loss 0.66 | Demographic disparity = 0.09
Client 3: accuracy loss: 4.93 | fairness loss 0.70 | Demographic disparity = 0.01
 
Avg Training Stats after 10 global rounds:
Training loss: 42.69 | Training accuracy: 77.32% | Training Demographic disparity: 0.0544
 
 Results after 10 global rounds of training:
|---- Avg Train Accuracy: 77.32%
|---- Test Accuracy: 80.00%
|---- Test Demographic disparity: 0.1246

 Total Run Time: 22.7378 sec


In [4]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, train_prn = False, adaptive_alpha = True, seed = 7)

  0%|          | 0/10 [00:00<?, ?it/s]


 | Global Training Round : 1 |



 10%|█         | 1/10 [00:03<00:28,  3.12s/it]

Client 0: accuracy loss: 2.67 | fairness loss 0.51 | Demographic disparity = 0.56
Client 1: accuracy loss: 2.53 | fairness loss 0.94 | Demographic disparity = 0.36
Client 2: accuracy loss: 2.22 | fairness loss 0.78 | Demographic disparity = 0.35
 
Avg Training Stats after 1 global rounds:
Training loss: 38.28 | Training accuracy: 87.88% | Training Demographic disparity: 0.4057

 | Global Training Round : 2 |



 20%|██        | 2/10 [00:05<00:24,  3.05s/it]

Client 0: accuracy loss: 2.85 | fairness loss 0.36 | Demographic disparity = 0.38
Client 1: accuracy loss: 3.00 | fairness loss 0.63 | Demographic disparity = 0.26
Client 2: accuracy loss: 2.43 | fairness loss 0.54 | Demographic disparity = 0.25
 
Avg Training Stats after 2 global rounds:
Training loss: 45.11 | Training accuracy: 88.36% | Training Demographic disparity: 0.2802

 | Global Training Round : 3 |



 30%|███       | 3/10 [00:08<00:20,  2.94s/it]

Client 0: accuracy loss: 2.93 | fairness loss 0.32 | Demographic disparity = 0.29
Client 1: accuracy loss: 3.31 | fairness loss 0.58 | Demographic disparity = 0.20
Client 2: accuracy loss: 2.94 | fairness loss 0.53 | Demographic disparity = 0.12
 
Avg Training Stats after 3 global rounds:
Training loss: 45.50 | Training accuracy: 84.35% | Training Demographic disparity: 0.1786

 | Global Training Round : 4 |



 40%|████      | 4/10 [00:11<00:17,  2.89s/it]

Client 0: accuracy loss: 3.07 | fairness loss 0.31 | Demographic disparity = 0.22
Client 1: accuracy loss: 3.81 | fairness loss 0.59 | Demographic disparity = 0.12
Client 2: accuracy loss: 3.64 | fairness loss 0.55 | Demographic disparity = 0.05
 
Avg Training Stats after 4 global rounds:
Training loss: 44.96 | Training accuracy: 80.06% | Training Demographic disparity: 0.1065

 | Global Training Round : 5 |



 50%|█████     | 5/10 [00:14<00:14,  2.95s/it]

Client 0: accuracy loss: 3.24 | fairness loss 0.32 | Demographic disparity = 0.06
Client 1: accuracy loss: 4.33 | fairness loss 0.61 | Demographic disparity = 0.06
Client 2: accuracy loss: 4.33 | fairness loss 0.58 | Demographic disparity = 0.01
 
Avg Training Stats after 5 global rounds:
Training loss: 44.35 | Training accuracy: 76.74% | Training Demographic disparity: 0.0410

 | Global Training Round : 6 |



 60%|██████    | 6/10 [00:17<00:12,  3.09s/it]

Client 0: accuracy loss: 2.99 | fairness loss 0.39 | Demographic disparity = 0.23
Client 1: accuracy loss: 3.79 | fairness loss 0.73 | Demographic disparity = 0.12
Client 2: accuracy loss: 3.81 | fairness loss 0.68 | Demographic disparity = 0.04
 
Avg Training Stats after 6 global rounds:
Training loss: 44.10 | Training accuracy: 80.02% | Training Demographic disparity: 0.1000

 | Global Training Round : 7 |



 70%|███████   | 7/10 [00:21<00:09,  3.16s/it]

Client 0: accuracy loss: 3.08 | fairness loss 0.37 | Demographic disparity = 0.15
Client 1: accuracy loss: 4.03 | fairness loss 0.70 | Demographic disparity = 0.11
Client 2: accuracy loss: 4.09 | fairness loss 0.66 | Demographic disparity = 0.02
 
Avg Training Stats after 7 global rounds:
Training loss: 43.85 | Training accuracy: 78.72% | Training Demographic disparity: 0.0782

 | Global Training Round : 8 |



 80%|████████  | 8/10 [00:24<00:06,  3.07s/it]

Client 0: accuracy loss: 3.46 | fairness loss 0.33 | Demographic disparity = 0.02
Client 1: accuracy loss: 4.94 | fairness loss 0.63 | Demographic disparity = 0.01
Client 2: accuracy loss: 5.11 | fairness loss 0.63 | Demographic disparity = 0.05
 
Avg Training Stats after 8 global rounds:
Training loss: 43.49 | Training accuracy: 73.19% | Training Demographic disparity: 0.0137

 | Global Training Round : 9 |



 90%|█████████ | 9/10 [00:26<00:02,  2.96s/it]

Client 0: accuracy loss: 3.18 | fairness loss 0.39 | Demographic disparity = 0.15
Client 1: accuracy loss: 4.34 | fairness loss 0.74 | Demographic disparity = 0.08
Client 2: accuracy loss: 4.48 | fairness loss 0.71 | Demographic disparity = 0.00
 
Avg Training Stats after 9 global rounds:
Training loss: 43.37 | Training accuracy: 77.29% | Training Demographic disparity: 0.0585

 | Global Training Round : 10 |



100%|██████████| 10/10 [00:29<00:00,  2.97s/it]

Client 0: accuracy loss: 3.23 | fairness loss 0.38 | Demographic disparity = 0.15
Client 1: accuracy loss: 4.45 | fairness loss 0.72 | Demographic disparity = 0.06
Client 2: accuracy loss: 4.60 | fairness loss 0.69 | Demographic disparity = 0.00
 
Avg Training Stats after 10 global rounds:
Training loss: 43.24 | Training accuracy: 76.64% | Training Demographic disparity: 0.0497
 
 Results after 11 global rounds of training:
|---- Avg Train Accuracy: 76.64%
|---- Test Accuracy: 79.00%
|---- Test Demographic disparity: 0.1478

 Total Run Time: 29.7363 sec


In [5]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, ret = True, adaptive_alpha = True, seed = 7)

100%|██████████| 10/10 [00:27<00:00,  2.71s/it]


(0.79, 0.1478048780487805)

In [6]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, ret = True, adaptive_alpha = True, seed = 7)

100%|██████████| 10/10 [00:33<00:00,  3.39s/it]


(0.79, 0.1478048780487805)

In [7]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, ret = True, adaptive_alpha = True, seed = 7)

100%|██████████| 10/10 [00:27<00:00,  2.74s/it]


(0.79, 0.1478048780487805)

In [8]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, ret = True, adaptive_alpha = True, seed = 7)

100%|██████████| 10/10 [00:26<00:00,  2.62s/it]


(0.79, 0.1478048780487805)

In [4]:
train_dataset = synthetic_info[0]
clients_idx = synthetic_info[2]

In [12]:
np.array(torch.tensor(clients_idx[0][train_dataset.sen[clients_idx[0]] == 1] > 500, dtype = torch.bool)).mean()

0.6707589285714286

In [14]:
torch.max(torch.tensor([1,2]),1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [14]:
np.array([]).mean()

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Mean of empty slice.
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan

In [26]:
test_dataset = synthetic_info[1]


[0,
 4,
 8,
 10,
 12,
 15,
 18,
 19,
 20,
 23,
 24,
 25,
 28,
 30,
 31,
 32,
 39,
 41,
 43,
 45,
 51,
 52,
 54,
 56,
 58,
 59,
 63,
 65,
 67,
 71,
 72,
 73,
 77,
 80,
 82,
 83,
 85,
 86,
 88,
 92,
 96]