In [1]:
from sims import *

In [2]:
synthetic_info = dataGenerate(seed = 7, train_samples = 3000, test_samples = 100)

In [3]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "threshold adjusting", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 1, local_epochs = 1, alpha = 1, train_prn = False, adaptive_alpha = True, seed = 7)

  0%|          | 0/1 [00:00<?, ?it/s]


 | Global Training Round : 1 |

Client 0: accuracy loss: 19.98 | fairness loss 0.94 | Demographic disparity = 0.56


100%|██████████| 1/1 [00:00<00:00,  4.23it/s]

Client 1: accuracy loss: 16.05 | fairness loss 1.55 | Demographic disparity = 0.35
Client 2: accuracy loss: 11.86 | fairness loss 1.26 | Demographic disparity = 0.33
 
Avg Training Stats after 1 global rounds:
Training loss: 243.05 | Validation accuracy: 15.67% | Validation Demographic disparity: 0.3799
tensor([ 470.7816, -470.7816])
tensor([ 168.0826, -168.0826])
tensor([ 80.5182, -80.5182])
 
 Results after 1 global rounds of training:
|---- Avg Train Accuracy: 15.67%
|---- Test Accuracy: 16.00%
|---- Test Demographic disparity: 0.4505

 Total Run Time: 0.3978 sec


In [4]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, train_prn = False, adaptive_alpha = True, seed = 7)

  0%|          | 0/10 [00:00<?, ?it/s]


 | Global Training Round : 1 |

tensor([[ -1.0656,  87.3095,   1.7280],
        [  1.0656, -87.3095,  -1.7280]])
tensor([[ 11.1565,  52.8633,   2.6653],
        [-11.1566, -52.8633,  -2.6653]])
tensor([[-12.7808,  70.2873,   1.1268],
        [ 12.7808, -70.2873,  -1.1268]])
tensor([[ 10.2864,  63.0212,   0.2507],
        [-10.2864, -63.0212,  -0.2507]])
tensor([[  0.0712,  69.6396,   0.6133],
        [ -0.0712, -69.6396,  -0.6133]])
tensor([[  5.7386,  64.8855,   0.4362],
        [ -5.7386, -64.8855,  -0.4362]])
tensor([[ -3.5400,  52.8415,  -0.7821],
        [  3.5399, -52.8415,   0.7821]])
tensor([[  5.1060,  55.9233,   1.4781],
        [ -5.1060, -55.9232,  -1.4781]])
tensor([[ 16.0600,  62.8944,   1.6949],
        [-16.0600, -62.8944,  -1.6949]])
tensor([[-19.0199,  67.6278,  -0.1963],
        [ 19.0199, -67.6278,   0.1963]])
tensor([[  3.1936,  61.3095,  -0.1577],
        [ -3.1936, -61.3095,   0.1577]])
tensor([[-16.3412,  60.7551,   1.2549],
        [ 16.3412, -60.7551,  -1.254

tensor([[ -8.1767,  10.5231,  -0.0348],
        [  8.1767, -10.5231,   0.0348]])
tensor([[-10.2213,  11.7886,  -1.4676],
        [ 10.2213, -11.7886,   1.4676]])
tensor([[-0.2051,  8.5936,  0.4901],
        [ 0.2051, -8.5936, -0.4901]])
tensor([[  4.9952,  16.1166,  -0.1376],
        [ -4.9952, -16.1166,   0.1376]])
tensor([[-7.4372,  8.0456,  0.1763],
        [ 7.4372, -8.0456, -0.1763]])
tensor([[-3.0127,  3.4933, -3.4156],
        [ 3.0127, -3.4933,  3.4156]])
tensor([[ -1.0579,  10.6945,  -0.7875],
        [  1.0579, -10.6945,   0.7875]])
tensor([[ -5.5342,  11.5468,  -0.5810],
        [  5.5342, -11.5468,   0.5810]])
tensor([[ 0.0602,  5.6912, -1.5548],
        [-0.0602, -5.6912,  1.5548]])
tensor([[ 2.6496,  6.4610,  1.9361],
        [-2.6496, -6.4610, -1.9361]])
tensor([[  7.2026,  11.6691,  -0.5152],
        [ -7.2026, -11.6691,   0.5152]])
tensor([[-0.5040,  3.3017,  0.2944],
        [ 0.5040, -3.3017, -0.2944]])
tensor([[  5.5815,  10.1898,  -1.2737],
        [ -5.5815, -10.1

tensor([[  3.8012,  22.2414,  -2.3762],
        [ -3.8012, -22.2414,   2.3762]])
tensor([[  1.4648,  13.5985,  -1.6756],
        [ -1.4648, -13.5985,   1.6756]])
tensor([[ 1.4529,  5.9559,  0.1388],
        [-1.4529, -5.9559, -0.1388]])
tensor([[  3.5185,  21.9608,  -2.3163],
        [ -3.5185, -21.9608,   2.3163]])
tensor([[ -6.7231,  24.2833,  -0.8227],
        [  6.7231, -24.2833,   0.8227]])
tensor([[ -6.1210,  20.0189,  -1.9520],
        [  6.1210, -20.0189,   1.9520]])
tensor([[ 10.7769,  21.6710,   0.7395],
        [-10.7769, -21.6710,  -0.7395]])
tensor([[ 1.5091,  8.4110, -0.5954],
        [-1.5091, -8.4110,  0.5954]])
tensor([[  6.2093,  12.8390,  -1.6658],
        [ -6.2093, -12.8390,   1.6658]])
tensor([[ 5.8078,  6.5172, -1.0947],
        [-5.8078, -6.5172,  1.0947]])
tensor([[ -2.0531,  18.9391,  -2.4464],
        [  2.0531, -18.9391,   2.4464]])
tensor([[ -2.1476,  17.5840,   1.1570],
        [  2.1476, -17.5840,  -1.1570]])
tensor([[  5.0683,  15.1479,  -1.5105],
      

tensor([[ 4.8929,  2.0848,  1.8268],
        [-4.8929, -2.0848, -1.8268]])
tensor([[ 0.3462,  8.4064,  0.4380],
        [-0.3462, -8.4064, -0.4380]])
tensor([[ 6.7862, -5.4244, -2.2224],
        [-6.7862,  5.4244,  2.2224]])
tensor([[ 13.3272,   8.3480,   2.9732],
        [-13.3272,  -8.3480,  -2.9732]])
tensor([[-11.7619,  -0.9085,  -3.1713],
        [ 11.7619,   0.9085,   3.1713]])
tensor([[ -8.7503,  10.5132,  -2.0025],
        [  8.7503, -10.5132,   2.0025]])
tensor([[ 2.0340,  4.0154, -1.4614],
        [-2.0340, -4.0154,  1.4614]])
tensor([[ 5.2233,  3.7014,  1.6853],
        [-5.2233, -3.7014, -1.6853]])
tensor([[-2.1499, -0.8961, -0.0791],
        [ 2.1499,  0.8961,  0.0791]])
tensor([[ 9.4664,  3.0060,  2.8112],
        [-9.4664, -3.0060, -2.8112]])
tensor([[ 5.2262,  3.3993,  2.0103],
        [-5.2262, -3.3993, -2.0103]])
tensor([[-9.0732,  3.2155, -2.6891],
        [ 9.0732, -3.2155,  2.6891]])
tensor([[ 0.2914,  6.5933, -2.3789],
        [-0.2914, -6.5933,  2.3789]])
tensor(

tensor([[  4.8169,  11.7486,   1.7591],
        [ -4.8169, -11.7486,  -1.7591]])
tensor([[ 1.1095,  8.1328, -0.5031],
        [-1.1095, -8.1328,  0.5031]])
tensor([[  2.5024,  12.8766,   0.0895],
        [ -2.5024, -12.8766,  -0.0895]])
tensor([[ -6.1123,  12.1076,  -1.6560],
        [  6.1123, -12.1076,   1.6560]])
tensor([[ 8.7042,  9.9723, -1.0741],
        [-8.7042, -9.9723,  1.0741]])
tensor([[ -4.3485,  17.0073,   0.8370],
        [  4.3485, -17.0073,  -0.8370]])
tensor([[-11.1840,  12.3436,  -2.0216],
        [ 11.1840, -12.3436,   2.0216]])
tensor([[-19.6391,   7.6327,  -2.8654],
        [ 19.6391,  -7.6327,   2.8654]])
tensor([[-0.4777,  9.1709,  0.4351],
        [ 0.4777, -9.1709, -0.4351]])
tensor([[ -0.3514,  12.7501,   0.4374],
        [  0.3514, -12.7501,  -0.4374]])
tensor([[-15.4503,  15.0976,  -1.0963],
        [ 15.4503, -15.0976,   1.0963]])
tensor([[ 4.0286,  9.8223,  0.2527],
        [-4.0286, -9.8223, -0.2527]])
tensor([[ -7.0108,  10.2404,  -1.2447],
        [  7

  0%|          | 0/10 [00:04<?, ?it/s]

tensor([[-5.0129,  9.7173, -0.8945],
        [ 5.0129, -9.7173,  0.8945]])
tensor([[-4.7687,  2.2948, -1.0445],
        [ 4.7687, -2.2948,  1.0445]])
tensor([[ 4.7491, -0.7634, -0.9282],
        [-4.7491,  0.7634,  0.9282]])
tensor([[ 12.9506,   6.2744,  -0.5959],
        [-12.9506,  -6.2744,   0.5959]])
tensor([[-5.5983,  5.4600, -2.2362],
        [ 5.5983, -5.4600,  2.2362]])
tensor([[ 7.3607, -0.9133,  1.9148],
        [-7.3607,  0.9133, -1.9148]])
tensor([[-6.0947,  6.6047, -2.5658],
        [ 6.0947, -6.6047,  2.5658]])
tensor([[-0.4548,  9.4818, -0.1290],
        [ 0.4548, -9.4818,  0.1290]])
tensor([[ 11.7023,   6.3619,   0.9416],
        [-11.7023,  -6.3619,  -0.9416]])
tensor([[-2.3149,  3.5138, -2.2289],
        [ 2.3149, -3.5138,  2.2289]])
tensor([[ 8.8571,  2.6470,  0.0136],
        [-8.8570, -2.6470, -0.0136]])
tensor([[ 1.4481,  8.3092, -3.1394],
        [-1.4481, -8.3092,  3.1394]])


KeyboardInterrupt: 

In [4]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, train_prn = False, adaptive_alpha = True, seed = 7)

  0%|          | 0/10 [00:00<?, ?it/s]


 | Global Training Round : 1 |



 10%|█         | 1/10 [00:03<00:28,  3.12s/it]

Client 0: accuracy loss: 2.67 | fairness loss 0.51 | Demographic disparity = 0.56
Client 1: accuracy loss: 2.53 | fairness loss 0.94 | Demographic disparity = 0.36
Client 2: accuracy loss: 2.22 | fairness loss 0.78 | Demographic disparity = 0.35
 
Avg Training Stats after 1 global rounds:
Training loss: 38.28 | Training accuracy: 87.88% | Training Demographic disparity: 0.4057

 | Global Training Round : 2 |



 20%|██        | 2/10 [00:05<00:24,  3.05s/it]

Client 0: accuracy loss: 2.85 | fairness loss 0.36 | Demographic disparity = 0.38
Client 1: accuracy loss: 3.00 | fairness loss 0.63 | Demographic disparity = 0.26
Client 2: accuracy loss: 2.43 | fairness loss 0.54 | Demographic disparity = 0.25
 
Avg Training Stats after 2 global rounds:
Training loss: 45.11 | Training accuracy: 88.36% | Training Demographic disparity: 0.2802

 | Global Training Round : 3 |



 30%|███       | 3/10 [00:08<00:20,  2.94s/it]

Client 0: accuracy loss: 2.93 | fairness loss 0.32 | Demographic disparity = 0.29
Client 1: accuracy loss: 3.31 | fairness loss 0.58 | Demographic disparity = 0.20
Client 2: accuracy loss: 2.94 | fairness loss 0.53 | Demographic disparity = 0.12
 
Avg Training Stats after 3 global rounds:
Training loss: 45.50 | Training accuracy: 84.35% | Training Demographic disparity: 0.1786

 | Global Training Round : 4 |



 40%|████      | 4/10 [00:11<00:17,  2.89s/it]

Client 0: accuracy loss: 3.07 | fairness loss 0.31 | Demographic disparity = 0.22
Client 1: accuracy loss: 3.81 | fairness loss 0.59 | Demographic disparity = 0.12
Client 2: accuracy loss: 3.64 | fairness loss 0.55 | Demographic disparity = 0.05
 
Avg Training Stats after 4 global rounds:
Training loss: 44.96 | Training accuracy: 80.06% | Training Demographic disparity: 0.1065

 | Global Training Round : 5 |



 50%|█████     | 5/10 [00:14<00:14,  2.95s/it]

Client 0: accuracy loss: 3.24 | fairness loss 0.32 | Demographic disparity = 0.06
Client 1: accuracy loss: 4.33 | fairness loss 0.61 | Demographic disparity = 0.06
Client 2: accuracy loss: 4.33 | fairness loss 0.58 | Demographic disparity = 0.01
 
Avg Training Stats after 5 global rounds:
Training loss: 44.35 | Training accuracy: 76.74% | Training Demographic disparity: 0.0410

 | Global Training Round : 6 |



 60%|██████    | 6/10 [00:17<00:12,  3.09s/it]

Client 0: accuracy loss: 2.99 | fairness loss 0.39 | Demographic disparity = 0.23
Client 1: accuracy loss: 3.79 | fairness loss 0.73 | Demographic disparity = 0.12
Client 2: accuracy loss: 3.81 | fairness loss 0.68 | Demographic disparity = 0.04
 
Avg Training Stats after 6 global rounds:
Training loss: 44.10 | Training accuracy: 80.02% | Training Demographic disparity: 0.1000

 | Global Training Round : 7 |



 70%|███████   | 7/10 [00:21<00:09,  3.16s/it]

Client 0: accuracy loss: 3.08 | fairness loss 0.37 | Demographic disparity = 0.15
Client 1: accuracy loss: 4.03 | fairness loss 0.70 | Demographic disparity = 0.11
Client 2: accuracy loss: 4.09 | fairness loss 0.66 | Demographic disparity = 0.02
 
Avg Training Stats after 7 global rounds:
Training loss: 43.85 | Training accuracy: 78.72% | Training Demographic disparity: 0.0782

 | Global Training Round : 8 |



 80%|████████  | 8/10 [00:24<00:06,  3.07s/it]

Client 0: accuracy loss: 3.46 | fairness loss 0.33 | Demographic disparity = 0.02
Client 1: accuracy loss: 4.94 | fairness loss 0.63 | Demographic disparity = 0.01
Client 2: accuracy loss: 5.11 | fairness loss 0.63 | Demographic disparity = 0.05
 
Avg Training Stats after 8 global rounds:
Training loss: 43.49 | Training accuracy: 73.19% | Training Demographic disparity: 0.0137

 | Global Training Round : 9 |



 90%|█████████ | 9/10 [00:26<00:02,  2.96s/it]

Client 0: accuracy loss: 3.18 | fairness loss 0.39 | Demographic disparity = 0.15
Client 1: accuracy loss: 4.34 | fairness loss 0.74 | Demographic disparity = 0.08
Client 2: accuracy loss: 4.48 | fairness loss 0.71 | Demographic disparity = 0.00
 
Avg Training Stats after 9 global rounds:
Training loss: 43.37 | Training accuracy: 77.29% | Training Demographic disparity: 0.0585

 | Global Training Round : 10 |



100%|██████████| 10/10 [00:29<00:00,  2.97s/it]

Client 0: accuracy loss: 3.23 | fairness loss 0.38 | Demographic disparity = 0.15
Client 1: accuracy loss: 4.45 | fairness loss 0.72 | Demographic disparity = 0.06
Client 2: accuracy loss: 4.60 | fairness loss 0.69 | Demographic disparity = 0.00
 
Avg Training Stats after 10 global rounds:
Training loss: 43.24 | Training accuracy: 76.64% | Training Demographic disparity: 0.0497
 
 Results after 11 global rounds of training:
|---- Avg Train Accuracy: 76.64%
|---- Test Accuracy: 79.00%
|---- Test Demographic disparity: 0.1478

 Total Run Time: 29.7363 sec


In [5]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, ret = True, adaptive_alpha = True, seed = 7)

100%|██████████| 10/10 [00:27<00:00,  2.71s/it]


(0.79, 0.1478048780487805)

In [6]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, ret = True, adaptive_alpha = True, seed = 7)

100%|██████████| 10/10 [00:33<00:00,  3.39s/it]


(0.79, 0.1478048780487805)

In [7]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, ret = True, adaptive_alpha = True, seed = 7)

100%|██████████| 10/10 [00:27<00:00,  2.74s/it]


(0.79, 0.1478048780487805)

In [8]:
train(logReg(num_features=3, num_classes=2), synthetic_info,
      option = "FairBatch", optimizer = 'adam', learning_rate = 0.005, metric = "Demographic disparity",
      num_rounds = 10, local_epochs = 30, alpha = 1, ret = True, adaptive_alpha = True, seed = 7)

100%|██████████| 10/10 [00:26<00:00,  2.62s/it]


(0.79, 0.1478048780487805)

In [9]:
train_dataset = synthetic_info[0]
clients_idx = synthetic_info[2]

In [12]:
clients_idx[0][train_dataset.sen[clients_idx[0]] == 1]

array([ 306,   71, 1284,   83,  925,  467,   25, 1470,  561, 1022, 1161,
        538,  767,  976,  703, 1318,  334,  794, 1049, 1272,  879,  150,
        193,  757, 1107,  100,  500,  274,  940,  653, 1237, 1165, 1506,
        272,  753,   65,  133, 1466,   58, 1389,  643, 1175,  995,  438,
        841,  678, 1130,  149, 1025,  203, 1299, 1018, 1279,  231,  964,
       1307,  761,   92,  199, 1288,  556,  656, 1336,  894, 1030,  317,
       1344, 1392,  429, 1066,  491,  244,  942, 1222,  518, 1005,  785,
       1116,  265, 1217,  680, 1113,  368,   19, 1108,  607,  558,  572,
       1026,  555,  384,  450,  871,  486,  569,  285,  650, 1011, 1224,
       1474,  290, 1410, 1385, 1241,  243,  295, 1139,  506, 1078, 1218,
         32,  872,  403,  922,  143,  715,   12,  339,  787,  304, 1027,
       1313,  720,  599,  576,  735,    5, 1019, 1324,  367,  121,  176,
         94,  419,  534, 1207,  499, 1247,  663, 1388, 1145, 1244,  278,
       1436,  142,  788,  108,  992,   15,  247,  8

In [14]:
torch.max(torch.tensor([1,2]),1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [15]:
torch.tensor([1,2])

tensor([1, 2])

In [26]:
test_dataset = synthetic_info[1]


[0,
 4,
 8,
 10,
 12,
 15,
 18,
 19,
 20,
 23,
 24,
 25,
 28,
 30,
 31,
 32,
 39,
 41,
 43,
 45,
 51,
 52,
 54,
 56,
 58,
 59,
 63,
 65,
 67,
 71,
 72,
 73,
 77,
 80,
 82,
 83,
 85,
 86,
 88,
 92,
 96]