In [1]:
import numpy as np
import pandas as pd
import copy
from utils import *

In [8]:
def nsfData(q = (0.99, 0.01), theta = (0.38/0.99, -0.5), train_samples = 3000, test_samples = 300):
    clients_idx = [np.arange(0,train_samples//2,1), np.arange(train_samples//2, train_samples//2*2, 1)]
    train_data, test_data = [], []

    for c in range(2):
        a = np.random.binomial(n = 1, p = q[c], size = train_samples//2 + test_samples//2)
        def prod_x(a):
            if a:
                return np.random.binomial(n=1, p=1/2+theta[c], size=1)
            else:
                return np.random.binomial(n=1, p=1/2, size=1)
        prod_x_v = np.vectorize(prod_x)
        x = prod_x_v(a)
        y = copy.deepcopy(x)
        data = pd.DataFrame(zip(x,a,y), columns = ["x", "a", "y"])
        train_data.append(data[:train_samples//2])
        test_data.append(data[train_samples//2:])
    train_data = pd.concat(train_data)
    test_data = pd.concat(test_data)
    train_dataset = LoadData(train_data, "y", "a")
    test_dataset = LoadData(test_data, "y", "a")
return [train_dataset, test_dataset, client_idx]

In [9]:
nsfData()

[1 1 1 ... 1 1 1]
[0 0 0 ... 0 0 0]


In [12]:
a = np.random.binomial(n = 1, p = 0.99, size = 1500 + 150)

In [3]:
q = (0.99, 0.01)
theta = (0.38/0.99, -0.5)
train_samples = 3000
test_samples = 300

In [15]:
clients_idx = []
train_data, test_data = [], []

for c in range(2):
    a = np.random.binomial(n = 1, p = q[c], size = train_samples//2 + test_samples//2)
    def prod_x(a):
        if a:
            return np.random.binomial(n=1, p=1/2+theta[c], size=1)
        else:
            return np.random.binomial(n=1, p=1/2, size=1)
    prod_x_v = np.vectorize(prod_x)
    x = prod_x_v(a)
    y = copy.deepcopy(x)
    data = pd.DataFrame(zip(x,a,y), columns = ["x", "a", "y"])
    train_data.append(data[:train_samples//2])
    test_data.append(data[train_samples//2:])
train_data = pd.concat(train_data).reset_index(drop=True)
test_data = pd.concat(test_data).reset_index(drop=True)
train_data = train_data.sample(frac = 1)
clients_idx[0] = np.where(train_data.index < train_samples//2)[0]
clients_idx[1] = np.where(train_data.index >= train_samples//2)[0]
train_data = train_data.reset_index(drop=True)

In [16]:
train_data.index

Int64Index([1198,  541, 2895,  800, 2131,  912, 1959, 1637, 2291, 1584,
            ...
            1399, 1429, 1348,    9, 1958,  807, 2633,  214, 2909, 1558],
           dtype='int64', length=3000)

In [8]:
clients_idx[0] = train_data.index[clients_idx[0]]

In [9]:
clients_idx[0] 

Int64Index([1489,  466, 1386, 1196, 1142,  807,  976, 1050, 1304,  338,
            ...
             241,   12,  526, 1421,  313,  425,  146, 1378, 1066,  219],
           dtype='int64', length=1500)

In [19]:
np.where(train_data.index < train_samples//2)

(array([   0,    1,    3, ..., 2993, 2995, 2997]),)

In [18]:
sum(train_data.index < (train_samples//2))

1500